using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using LeakGuard.Models;

namespace LeakGuard.Reports
{
    public class IncidentReportDocument : IDocument
    {
        private readonly List<Incident> _incidents;
        private readonly string _generatedBy;
        private readonly DateTime _generatedAt;
        private readonly string _filterScope;

        // Brand Colors
        private const string ColPrimary   = "#0D6EFD";
        private const string ColDanger    = "#DC3545";
        private const string ColWarning   = "#E6A817";
        private const string ColInfo      = "#0DCAF0";
        private const string ColDark      = "#111827";
        private const string ColPanel     = "#1C2333";
        private const string ColBorder    = "#2D3A50";
        private const string ColMuted     = "#6B7A99";
        private const string ColWhite     = "#FFFFFF";
        private const string ColAmber     = "#E6A817";

        public IncidentReportDocument(IEnumerable<Incident> incidents, string generatedBy, DateTime generatedAt, string filterScope = "All incidents (unfiltered)")
        {
            _incidents   = incidents.ToList();
            _generatedBy = generatedBy;
            _generatedAt = generatedAt;
            _filterScope = filterScope;
        }

        public DocumentMetadata GetMetadata() => new DocumentMetadata
        {
            Title    = "LeakGuard — Forensic Incident Report",
            Author   = _generatedBy,
            Subject  = "Data Loss Prevention Incident Report",
            Keywords = "LeakGuard, DLP, Security, Incidents, Forensic",
            CreationDate = _generatedAt
        };

        public DocumentSettings GetSettings() => DocumentSettings.Default;

        public void Compose(IDocumentContainer container)
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4.Landscape()); // Landscape gives more table width
                page.Margin(24);
                page.DefaultTextStyle(t => t.FontFamily("Arial").FontColor(ColWhite).FontSize(9));
                page.Background().Background(ColDark);

                page.Header().Element(Header);
                page.Content().Element(Content);
                page.Footer().Element(Footer);
            });
        }

        // ─────────────────────────── HEADER ───────────────────────────

        private void Header(IContainer c)
        {
            int blocked     = _incidents.Count(i => i.ActionType?.ActionName == "Blocked");
            int quarantined = _incidents.Count(i => i.ActionType?.ActionName == "Quarantined");
            int alerted     = _incidents.Count(i => i.ActionType?.ActionName == "Alerted");

            c.Background(ColPanel)
             .Border(1).BorderColor(ColBorder)
             .PaddingHorizontal(20).PaddingVertical(14)
             .Column(col =>
             {
                 // ── Top row: branding + meta ──
                 col.Item().Row(row =>
                 {
                     // LEFT: Logo area
                     row.RelativeItem().Column(inner =>
                     {
                         inner.Item().Row(r =>
                         {
                             r.AutoItem()
                                 .Width(6).Height(36)
                                 .Background(ColPrimary);

                             r.AutoItem().Width(10);

                             r.RelativeItem().Column(brand =>
                             {
                                 brand.Item()
                                     .Text("LeakGuard DLP")
                                     .FontSize(20).Bold().FontColor(ColWhite);
                                 brand.Item()
                                     .Text("Data Loss Prevention System  •  Forensic Incident Report")
                                     .FontSize(8).FontColor(ColMuted);
                             });
                         });
                     });

                     // RIGHT: Meta info (fixed 280pt wide)
                     row.ConstantItem(280)
                         .Border(1).BorderColor(ColBorder)
                         .Background(ColDark)
                         .PaddingHorizontal(12).PaddingVertical(8)
                         .Column(meta =>
                         {
                             MetaLine(meta, "Report Date",   _generatedAt.ToLocalTime().ToString("MMMM dd, yyyy"));
                             MetaLine(meta, "Time",          _generatedAt.ToLocalTime().ToString("HH:mm:ss") + " (Local)");
                             MetaLine(meta, "Generated By",  _generatedBy);
                             MetaLine(meta, "Report Scope",  _filterScope);
                             MetaLine(meta, "Classification","CONFIDENTIAL — Authorized Personnel Only");
                         });
                 });

                 col.Item().Height(10);

                 // ── Bottom row: 4 stat cards ──
                 col.Item().Row(row =>
                 {
                     row.RelativeItem().Element(c2 => StatCard(c2, "TOTAL INCIDENTS", _incidents.Count.ToString(), ColPrimary));
                     row.AutoItem().Width(8);
                     row.RelativeItem().Element(c2 => StatCard(c2, "BLOCKED",     blocked.ToString(),     ColDanger));
                     row.AutoItem().Width(8);
                     row.RelativeItem().Element(c2 => StatCard(c2, "QUARANTINED", quarantined.ToString(), ColWarning));
                     row.AutoItem().Width(8);
                     row.RelativeItem().Element(c2 => StatCard(c2, "ALERTED",     alerted.ToString(),     ColInfo));
                 });
             });
        }

        private static void MetaLine(ColumnDescriptor col, string label, string value)
        {
            col.Item().PaddingBottom(3).Row(r =>
            {
                r.ConstantItem(90).Text(label + ":").FontSize(7.5f).FontColor(ColMuted);
                r.RelativeItem().Text(value).FontSize(7.5f).Bold().FontColor(ColWhite);
            });
        }

        private static void StatCard(IContainer c, string label, string value, string color)
        {
            c.Border(1).BorderColor(ColBorder)
             .Background(ColDark)
             .PaddingHorizontal(10).PaddingVertical(8)
             .Column(col =>
             {
                 col.Item().Text(value).FontSize(20).Bold().FontColor(color);
                 col.Item().Text(label).FontSize(7).FontColor(ColMuted);
             });
        }

        // ─────────────────────────── CONTENT ───────────────────────────

        private void Content(IContainer c)
        {
            c.PaddingTop(14).Column(col =>
            {
                // Section heading
                col.Item().PaddingBottom(8).Row(r =>
                {
                    r.AutoItem().Width(4).Height(16).Background(ColPrimary);
                    r.AutoItem().Width(8);
                    r.RelativeItem()
                        .Text($"Incident Records  ({_incidents.Count} total)")
                        .FontSize(12).Bold().FontColor(ColWhite);
                });

                // Table
                col.Item().Table(table =>
                {
                    // Define columns
                    table.ColumnsDefinition(cols =>
                    {
                        cols.ConstantColumn(34);   // #
                        cols.RelativeColumn(1.4f); // Timestamp
                        cols.RelativeColumn(1.2f); // Endpoint
                        cols.RelativeColumn(1.6f); // Rule
                        cols.RelativeColumn(0.9f); // Action
                        cols.RelativeColumn(1.8f); // Matched
                        cols.RelativeColumn(2.8f); // File Path
                    });

                    // Header row
                    table.Header(h =>
                    {
                        static IContainer HeaderCell(IContainer c) =>
                            c.Background(ColPrimary)
                             .PaddingHorizontal(6).PaddingVertical(5);

                        h.Cell().Element(HeaderCell).Text("#").Bold().FontSize(8).FontColor(ColWhite);
                        h.Cell().Element(HeaderCell).Text("Timestamp").Bold().FontSize(8).FontColor(ColWhite);
                        h.Cell().Element(HeaderCell).Text("Endpoint").Bold().FontSize(8).FontColor(ColWhite);
                        h.Cell().Element(HeaderCell).Text("Rule Triggered").Bold().FontSize(8).FontColor(ColWhite);
                        h.Cell().Element(HeaderCell).Text("Action").Bold().FontSize(8).FontColor(ColWhite);
                        h.Cell().Element(HeaderCell).Text("Matched Content").Bold().FontSize(8).FontColor(ColWhite);
                        h.Cell().Element(HeaderCell).Text("File Path").Bold().FontSize(8).FontColor(ColWhite);
                    });

                    // Data rows
                    for (int i = 0; i < _incidents.Count; i++)
                    {
                        var incident = _incidents[i];
                        var bg = i % 2 == 0 ? ColPanel : ColDark;

                        var actionName  = incident.ActionType?.ActionName ?? "Alerted";
                        var actionColor = actionName switch
                        {
                            "Blocked"     => ColDanger,
                            "Quarantined" => ColWarning,
                            _             => ColInfo
                        };

                        IContainer DataCell(IContainer cell) =>
                            cell.Background(bg)
                                .BorderBottom(1).BorderColor(ColBorder)
                                .PaddingHorizontal(6).PaddingVertical(4);

                        table.Cell().Element(DataCell)
                            .Text($"#{incident.IncidentID}").FontSize(7).FontColor(ColMuted);

                        table.Cell().Element(DataCell)
                            .Text(incident.Timestamp.ToLocalTime().ToString("MMM dd, yyyy\nHH:mm:ss"))
                            .FontSize(7).FontColor(ColMuted).LineHeight(1.3f);

                        table.Cell().Element(DataCell)
                            .Text(incident.Endpoint?.Hostname ?? "Unknown")
                            .FontSize(7.5f).FontColor(ColWhite);

                        table.Cell().Element(DataCell)
                            .Text(incident.Rule?.RuleName ?? "Unknown")
                            .FontSize(7.5f).FontColor(ColPrimary);

                        table.Cell().Element(DataCell)
                            .Text(actionName).FontSize(7.5f).Bold().FontColor(actionColor);

                        table.Cell().Element(DataCell)
                            .Text(Truncate(incident.MatchedText ?? "—", 60))
                            .FontSize(7).FontColor(ColAmber);

                        table.Cell().Element(DataCell)
                            .Text(Truncate(incident.FilePath ?? "—", 80))
                            .FontSize(6.5f).FontColor(ColMuted);
                    }

                    // Empty state
                    if (_incidents.Count == 0)
                    {
                        IContainer EmptyCell(IContainer cell) =>
                            cell.Background(ColPanel)
                                .PaddingHorizontal(6).PaddingVertical(20)
                                .AlignCenter();

                        for (int col2 = 0; col2 < 7; col2++)
                            table.Cell().Element(EmptyCell).Text(col2 == 3 ? "No incidents recorded." : "")
                                .FontSize(9).Italic().FontColor(ColMuted);
                    }
                });
            });
        }

        // ─────────────────────────── FOOTER ───────────────────────────

        private void Footer(IContainer c)
        {
            c.BorderTop(1).BorderColor(ColBorder)
             .PaddingTop(8)
             .Row(row =>
             {
                 row.RelativeItem().Column(col =>
                 {
                     col.Item()
                         .Text("LeakGuard — Data Loss Prevention System")
                         .FontSize(7.5f).Bold().FontColor(ColMuted);
                     col.Item()
                         .Text("This document is classified. Unauthorized distribution is prohibited.")
                         .FontSize(7).FontColor(ColBorder);
                 });

                 row.AutoItem().AlignRight().AlignMiddle().Text(t =>
                 {
                     t.Span("Page ").FontSize(7.5f).FontColor(ColMuted);
                     t.CurrentPageNumber().FontSize(7.5f).Bold().FontColor(ColWhite);
                     t.Span(" / ").FontSize(7.5f).FontColor(ColMuted);
                     t.TotalPages().FontSize(7.5f).Bold().FontColor(ColWhite);
                 });
             });
        }

        // ─────────────────────────── HELPERS ───────────────────────────

        private static string Truncate(string text, int max) =>
            string.IsNullOrEmpty(text) ? "—" :
            text.Length <= max ? text : text[..max] + "…";
    }
}
